"""accession

Revision ID: 1192c4f69d43
Revises: 436aabc6e771
Create Date: 2022-05-26 10:39:32.367993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1192c4f69d43'
down_revision = '436aabc6e771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
