"""ptype

Revision ID: 239ee79bf2e3
Revises: 1192c4f69d43
Create Date: 2022-05-26 10:45:06.388726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239ee79bf2e3'
down_revision = '1192c4f69d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('accession', sa.Text(), nullable=True))
    op.add_column('activity', sa.Column('protein_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'protein_type')
    op.drop_column('activity', 'accession')
    # ### end Alembic commands ###
