"""activity_id

Revision ID: 319828fdada3
Revises: b009d946fc26
Create Date: 2022-05-26 13:29:04.644754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319828fdada3'
down_revision = 'b009d946fc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('papyrus_activity_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'papyrus_activity_id')
    # ### end Alembic commands ###
