"""one2many

Revision ID: 4d3d349ee211
Revises: ccb68b675cbc
Create Date: 2022-05-26 11:30:11.913002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3d349ee211'
down_revision = 'ccb68b675cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cid', sa.Column('molecule_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cid', 'molecule', ['molecule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cid', type_='foreignkey')
    op.drop_column('cid', 'molecule_id')
    # ### end Alembic commands ###
