"""cid

Revision ID: 8bb1545a5008
Revises: de3cf0191503
Create Date: 2022-05-26 11:00:20.159778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb1545a5008'
down_revision = 'de3cf0191503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
