"""mapper

Revision ID: a56cddd55ba6
Revises: 8bb1545a5008
Create Date: 2022-05-26 11:02:35.888229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56cddd55ba6'
down_revision = '8bb1545a5008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
