"""one2many

Revision ID: b009d946fc26
Revises: 4d3d349ee211
Create Date: 2022-05-26 11:31:44.324948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b009d946fc26'
down_revision = '4d3d349ee211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
