"""one2many

Revision ID: ccb68b675cbc
Revises: 2d33c9b9a809
Create Date: 2022-05-26 11:28:20.471799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb68b675cbc'
down_revision = '2d33c9b9a809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cid_molecule_fkey', 'cid', type_='foreignkey')
    op.drop_column('cid', 'molecule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cid', sa.Column('molecule', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cid_molecule_fkey', 'cid', 'molecule', ['molecule'], ['id'])
    # ### end Alembic commands ###
