"""classification

Revision ID: de3cf0191503
Revises: 239ee79bf2e3
Create Date: 2022-05-26 10:54:44.604487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3cf0191503'
down_revision = '239ee79bf2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('protein_classification_fkey', 'protein', type_='foreignkey')
    op.drop_column('protein', 'classification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protein', sa.Column('classification', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('protein_classification_fkey', 'protein', 'classification', ['classification'], ['id'])
    # ### end Alembic commands ###
